[package]
name = "powerbuttond-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
evdev = { version = "0.13.0", features = ["tokio"] }
tokio = { version = "1.17", features = ["rt"] }
udev = "0.9.3"
